# SonarQube Community Edition Configuration
sonar:
  edition: ""  # Unset edition to use Community edition
  community:
    enabled: true  # Enable Community Edition

  # Image configuration
  image:
    tag: "latest"  # Use the latest stable version of SonarQube Community Edition

  # Database configuration (PostgreSQL by default)
  database:
    enabled: true  # Enable PostgreSQL database
    host: "postgresql"  # Name of the PostgreSQL host (can be set to an external DB hostname if needed)
    port: 5432  # Default PostgreSQL port
    name: "sonar-db"  # Name of the database for SonarQube
    user: "sonar"  # User for the SonarQube database
    password: "sonar"  # Set the password for the PostgreSQL user

  # Resource requests and limits
  resources:
    requests:
      cpu: "500m"  # Set CPU request to 500m
      memory: "1Gi"  # Set memory request to 1Gi
    limits:
      cpu: "2"  # Set CPU limit to 2
      memory: "4Gi"  # Set memory limit to 4Gi

  # Persistence configuration for SonarQube data
  persistence:
    enabled: true  # Enable persistence to store SonarQube data
    size: "10Gi"  # Set the persistent storage size to 10Gi
    storageClass: "default"  # Specify the storage class (use your AKS default or any other configured class)

  # Monitoring configuration
  monitoring:
    enabled: true  # Enable monitoring integration
    #passcode: "Welcome"  # Set the monitoring passcode to "Welcome"
    PasscodeSecretName: "Welcome"
    PasscodeSecretKey: "Welcome"

  # Ingress configuration (for exposing SonarQube via LoadBalancer)
  #ingress:
    #enabled: false  # Set to false since we are using LoadBalancer
    #hosts:
      #- name: "sonarqube.yourdomain.com"  # Replace with your domain if you want to use Ingress
    #annotations: {}  # Add any necessary annotations for your ingress controller

  # Service configuration (use LoadBalancer to expose SonarQube externally)
  service:
    type: LoadBalancer  # Expose SonarQube via LoadBalancer
    port: 9000  # The default SonarQube port
    targetPort: 9000  # Target port for the service
    loadBalancerIP: ""  # Leave empty to get an automatically assigned IP, or specify a static IP if needed

  # Admin user configuration
  admin:
    password: "sonar"  # Admin password for SonarQube (replace with a secure password)

  # Additional configurations (if you are using an external Elasticsearch or other custom configurations)
  elasticsearch:
    enabled: false  # Disable Elasticsearch if you're using an external Elasticsearch instance

